### ISSUE TITLE
rrule 2.6.5 is broken

### ISSUE THREAD

**Issue by naimo84** [jens-maus/node-ical#11] opened 2020-08-28 07:50 UTC
Hi Jens,

thanks for your great node-module. I'm using it in two of my projects 👍 

unfortunately the newest rrule 2.6.5 is broken. 
![image](https://user-images.githubusercontent.com/11535502/91535344-4d5fdd00-e913-11ea-9ed7-ed85bddef140.png)

I can fix it on my side, but it would be nice if you could do the same on yours 😉 

kind regards,
Benjamin

**Comment by jens-maus** [comment] 2020-08-29 08:01
Thanks, but this is a duplicate of #10

**Closed as completed by jens-maus** 2020-08-29 08:01 UTC
